version: '3'
services:

   application:
     build:
       context: .
       dockerfile: Dockerfile
       args:
         jarFile: ./build/libs/spring-boot-docker-compose-jacoco-test-coverage-0.0.1-SNAPSHOT.jar
     command: -m 2056m
     ports:
       - 8080:8080
       - 9999:9999
     volumes:
       - ./jacocoagent:/jacocoagent
       - ./jacocoreport:/jacocoreport
     entrypoint: [
     "java",
     "-Dcom.sun.management.jmxremote",
     "-Dcom.sun.management.jmxremote.local.only=false",
     "-Dcom.sun.management.jmxremote.ssl=false",
     "-Dcom.sun.management.jmxremote.authenticate=false",
     "-Dcom.sun.management.jmxremote.port=9999",
     "-Dcom.sun.management.jmxremote.rmi.port=9999",
     "-Djava.rmi.server.hostname=localhost",
     "-Djava.security.egd=file:/dev/./urandom",
     "-javaagent:/jacocoagent/jacocoagent.jar=output=file,destfile=/jacocoreport/coverage.exec,jmx=true",
     "-jar",
     "/app.jar"
     ]